"""Migration totale de toute les tables 

Revision ID: 182f82541366
Revises: 
Create Date: 2025-06-17 14:45:35.097694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182f82541366'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=False),
    sa.Column('date_publication', sa.Date(), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('disponible', sa.Integer(), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('est_admin', sa.Boolean(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emprunts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.Column('date_emprunt', sa.DateTime(), nullable=True),
    sa.Column('date_retour_prevue', sa.DateTime(), nullable=False),
    sa.Column('date_retour_effective', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livre_id'], ['livres.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprunts')
    op.drop_table('utilisateurs')
    op.drop_table('livres')
    # ### end Alembic commands ###
