"""ajout de la table categorie et d'autres fonctionnalités

Revision ID: 5a5fef6fc86f
Revises: 182f82541366
Create Date: 2025-06-17 15:42:24.526527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5fef6fc86f'
down_revision = '182f82541366'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    with op.batch_alter_table('livres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categorie_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'categories', ['categorie_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('livres', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('categorie_id')

    op.drop_table('categories')
    # ### end Alembic commands ###
